config/routes.rb
Rails.application.routes.draw do

  get 'dashboards/index', to: 'dashboards#index', as: 'dashboard'
  resources :dashboards, only: [:index, :create]

  mount LetterOpenerWeb::Engine, at: "/inbox" if Rails.env.development?
  devise_for :users
  resources :users, except: [ :index]
  root 'homepage#index'

  resources :articles do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :category
  belongs_to :user
  belongs_to :company
  validates :message, length: {minimum:10}
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :articles, dependent: :destroy
    has_many :article_users, through: :articles, source: :user
    has_many :article_companies, through: :articles, source: :company
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :articles, dependent: :destroy
    has_many :article_users, through: :articles, source: :user
    has_many :article_categories, through: :articles, source: :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :timeoutable, :trackable, :lockable

 
  validates :phone_number, numericality: { only_integer: true }, length: {is:8}
  validates :pseudo, length: {minimum:6},  presence: true, uniqueness:  true
  validates :adress, presence: true
  has_many :articles, dependent: :destroy
  has_many :article_companies, through: :articles, source: :company
  has_many :article_categories, through: :articles, source: :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:pseudo, :phone_number, :adress])
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :select_category, :select_company, :get_companies, only: [:new, :create, :edit, :update, :confirm]
  before_action :get_article_by_id, only: [:edit, :update]

  def index
    @articles = Article.all.order(created_at: :desc)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def confirm
    @article = current_user.articles.build(article_params)
    render :new if @article.invalid?
  end

  def update
    if @article.update(article_params)
      flash[:info] = "Article updated successfully"
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  def create
    @article = current_user.articles.new(article_params)
    @article.status = false
    if @article.save
      flash[:info] = "Article created successfully"
      redirect_to articles_path
    else
      render new_article_path
    end
  end

  def destroy
    Article.find(params[:id]).destroy
    flash[:danger] = "Article deleted successfully"
    redirect_to dashboard_path
  end

  private
  def select_category
    @select_category = []
    @select_category << ["Choose one category", ""]
    Category.all.order(name: :asc).each do |cat|
      @select_category << [cat.name, cat.id]
    end
  end

  def select_company
    @select_company = []
    @select_company << ["Choose one company", ""]
    Company.all.order(name: :asc).each do |comp|
      @select_company << [comp.name, comp.id]
    end
  end

  def article_params
    params.require(:article).permit(:category_id, :company_id, :message)
  end

  def get_article_by_id
    @article = Article.find(params[:id])
  end

  def get_companies
    @companies = Company.all.order(name: :asc)
  end

  def get_categories
    @categories = Category.all.order(name: :asc)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @articles = current_user.articles.order(created_at: :desc)
  end

  def create
    @article = Article.find(params[:article_id])
    @article.update(status: !@article.status)
    redirect_to dashboard_path
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
    skip_before_action :authenticate_user!, only: [:index]

    def index  
    end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new

  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.

  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
    def choose_new_or_edit
        if action_name == 'new' || action_name == 'create'
          confirm_articles_path
        elsif action_name == 'edit'
          article_path
        end
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width" />
    <title>BEST</title>
    <link rel="icon" type="image/png" href="/best-icon1.png" />
    <%= csrf_meta_tags %> <%= csp_meta_tag %> <%=
    stylesheet_link_tag'application', media: 'all', 'data-turbolinks-track':
    'reload' %> <%=javascript_include_tag 'application',
    'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="mb-4"><br></p>
    <%= render "partials/header" %>
    <%= yield %>
    <%= render "partials/footer" %>
  </body>
</html>

app/views/partials/_errors.html.erb
<% if @article.errors.any? %>
  <div class="alert alert-danger">
    <p><%= notice %></p>
    <ul>
    <% @article.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<div class="container">
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="/" class="nav-link px-2 text-muted">Accueil</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Contacts</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">A propos</a></li>
    </ul>
    <p class="text-center text-muted">© Août 2021 BEST, ALL RIGHTS RESERVED</p>
  </footer>
</div>

app/views/partials/_form.html.erb
<%= form_with(model: @article, local: true, url: choose_new_or_edit) do |form| %>
    <%= render "partials/errors" %>

    <div class="mb-3">
        <%= form.label :Category, class: "form-label" %>
        <%= form.select :category_id, @select_category, { wrapper: { class: 'has-warning', data: { foo: 'bar' } } }, {class:"form-select"} %> 
    </div>
    <div class="mb-3">
        <%= form.label :Company, class: "form-label" %>
        <%= form.select :company_id, @select_company, { wrapper: { class: 'has-warning', data: { foo: 'bar' } } }, class:"form-select" %>
    </div>
    <div class="mb-3">
        <%= form.label :Message, class: "form-label" %>
        <%= form.text_area :message, class: "form-control", id: "exampleInputEmail1" %>
        <div id="emailHelp" class="form-text">This area must contain minimum 10 characters</div>
    </div>
    <%= form.submit "Submit", class: "btn btn-primary mb-4" %>
<% end %>

app/views/partials/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top">
  <div class="container">
    <a class="navbar-brand" href="/">
        <strong>
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-award" viewBox="0 0 16 16">
            <path d="M9.669.864 8 0 6.331.864l-1.858.282-.842 1.68-1.337 1.32L2.6 6l-.306 1.854 1.337 1.32.842 1.68 1.858.282L8 12l1.669-.864 1.858-.282.842-1.68 1.337-1.32L13.4 6l.306-1.854-1.337-1.32-.842-1.68L9.669.864zm1.196 1.193.684 1.365 1.086 1.072L12.387 6l.248 1.506-1.086 1.072-.684 1.365-1.51.229L8 10.874l-1.355-.702-1.51-.229-.684-1.365-1.086-1.072L3.614 6l-.25-1.506 1.087-1.072.684-1.365 1.51-.229L8 1.126l1.356.702 1.509.229z"/>
            <path d="M4 11.794V16l4-1 4 1v-4.206l-2.018.306L8 13.126 6.018 12.1 4 11.794z"/>
            </svg> 
            BEST
        </strong>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0"></ul>
      <ul class="navbar-nav">
        <% if user_signed_in? %>
            <li><a class="nav-link" aria-current="page" href="/">Accueil</a></li>
            <li><a class="nav-link" aria-current="page" href="/articles">Articles</a></li>
            <li><a class="nav-link" href="#">Contacts</a></li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="bi bi-person-circle"></i> <%= current_user.pseudo %>
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="/dashboards/index">Dashboard</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="/users/sign_out" data-method="delete"><i class="bi bi-power"></i> Logout</a></li>
                </ul>
            </li>
            <li><a class="btn btn-success" href="/articles/new">Post <i class="bi bi-clipboard-plus"></i></a></li>
        <% else %>
            <li><a class="nav-link" href="/users/sign_up">Sign up</a></li>
            <li><a class="btn btn-light" href="/users/sign_in">Sign in</a></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/partials/_links.html.erb
<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "Forgot password?", new_password_path(resource_name), class:"forgot-password-link" %><br />
<% end %>

<p class="login-card-footer-text">
    <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
    Don't have an account? 
    <%= link_to "Sign up", new_registration_path(resource_name), class:"text-reset" %><br />
    <% end %>
    <%- if controller_name != 'sessions' %>
    You have an account ?
    <%= link_to "Log in", new_session_path(resource_name) %><br />
    <% end %>
    <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
    <% end %>
</p>